import { useMemo, useState, type ReactNode } from 'react'
import { createRoot } from 'react-dom/client'
import { Activity, AlertTriangle, ArrowUpRight, BarChart3, Bell, Building2, CheckCircle2, ChevronRight, CircleHelp, ClipboardCheck, FileCheck2, FileText, LayoutDashboard, Menu, Plus, Search, ShieldCheck, Sparkles, Users, X } from 'lucide-react'
import { DEMO_ACTIVITY, DEMO_BIDS, DEMO_TENDERS, type Bid, type Status, type UserRole, type Workspace } from './domain'
import './index.css'

type Metric = { label: string; value: string; detail: string; icon: ReactNode; tone: string }

function App() {
  const [role, setRole] = useState<UserRole>('OFFICER')
  const [workspace, setWorkspace] = useState<Workspace>('overview')
  const [mobileOpen, setMobileOpen] = useState(false)
  const [showRoleMenu, setShowRoleMenu] = useState(false)
  const [notice, setNotice] = useState('')

  const isOfficer = role === 'OFFICER'
  const pageTitle = workspace === 'overview' ? (isOfficer ? 'Officer overview' : 'Bidder overview') : workspace[0].toUpperCase() + workspace.slice(1)
  const pageSubtitle = isOfficer ? 'Monitor procurement activity, evidence quality and decisions in one place.' : 'Track opportunities, submissions and verification progress from one workspace.'

  function selectWorkspace(next: Workspace) {
    setWorkspace(next); setMobileOpen(false)
  }

  return <div className="app-shell">
    <aside className={mobileOpen ? 'sidebar sidebar-open' : 'sidebar'}>
      <div className="sidebar-brand"><div className="brand-mark"><Building2 /></div><div><strong>TenderHub</strong><span>SIH26100 platform</span></div></div>
      <div className="role-switcher"><span className="role-label">WORKSPACE</span><button onClick={() => setShowRoleMenu(!showRoleMenu)}><span><span className="role-dot" />{isOfficer ? 'Procurement Officer' : 'Bidder / Vendor'}</span><ChevronRight className={showRoleMenu ? 'rotate' : ''} /></button>{showRoleMenu && <div className="role-menu"><button onClick={() => { setRole('OFFICER'); setShowRoleMenu(false) }}>Procurement Officer</button><button onClick={() => { setRole('BIDDER'); setShowRoleMenu(false) }}>Bidder / Vendor</button></div>}</div>
      <nav className="side-nav" aria-label="Workspace navigation"><span className="nav-label">OPERATIONS</span><SideLink icon={<LayoutDashboard />} label="Overview" active={workspace === 'overview'} onClick={() => selectWorkspace('overview')} /><SideLink icon={<FileText />} label={isOfficer ? 'Tenders' : 'Available tenders'} active={workspace === 'tenders'} onClick={() => selectWorkspace('tenders')} /><SideLink icon={<ClipboardCheck />} label={isOfficer ? 'Bid review' : 'My applications'} active={workspace === 'bids'} onClick={() => selectWorkspace('bids')} /><SideLink icon={<FileCheck2 />} label="Documents" active={workspace === 'documents'} onClick={() => selectWorkspace('documents')} /><span className="nav-label nav-label-spaced">GOVERNANCE</span><SideLink icon={<Activity />} label="Audit trail" active={workspace === 'audit'} onClick={() => selectWorkspace('audit')} /></nav>
      <div className="sidebar-foot"><div className="ai-note"><Sparkles /><div><strong>AI decision support</strong><span>Human review is always required.</span></div></div><button className="help-link" onClick={() => setNotice('TenderHub support will be connected in a later phase.')}><CircleHelp />Help & guidance</button><div className="profile"><div className="avatar">{isOfficer ? 'RK' : 'AV'}</div><div><strong>{isOfficer ? 'Riya Kapoor' : 'Aarav Ventures'}</strong><span>{isOfficer ? 'Health procurement' : 'Verified vendor'}</span></div><button aria-label="More profile options"><span>•••</span></button></div></div>
    </aside>
    <main className="main-content"><header className="topbar"><button className="mobile-menu" onClick={() => setMobileOpen(!mobileOpen)} aria-label="Open navigation"><Menu /></button><div className="breadcrumbs"><span>Workspace</span><ChevronRight /><strong>{pageTitle}</strong></div><div className="top-actions"><span className="environment"><span className="status-dot" />Demo environment</span><button className="icon-button" aria-label="Notifications" onClick={() => setNotice('You have 3 notifications requiring attention.')}><Bell /><span className="notification-count">3</span></button><div className="top-avatar">{isOfficer ? 'RK' : 'AV'}</div></div></header><div className="page-content"><div className="page-heading"><div><p className="eyebrow">{isOfficer ? 'PROCUREMENT CONTROL CENTRE' : 'VENDOR WORKSPACE'}</p><h1>{pageTitle}</h1><p>{pageSubtitle}</p></div><div className="heading-actions">{isOfficer && <button className="button-primary" onClick={() => { setWorkspace('tenders'); setNotice('Tender creation workspace is ready for the next phase.') }}><Plus />Create tender</button>}<button className="button-secondary" onClick={() => setNotice('Reports are available after the Phase 4 tender workflow is connected.')}><BarChart3 />Reports <ArrowUpRight /></button></div></div>{notice && <div className="notice"><CheckCircle2 /><span>{notice}</span><button onClick={() => setNotice('')} aria-label="Dismiss notice"><X /></button></div>}{workspace === 'overview' ? <Overview isOfficer={isOfficer} onNavigate={selectWorkspace} /> : <WorkspacePage workspace={workspace} isOfficer={isOfficer} onNotice={setNotice} />}</div></main>
  </div>
}

function Overview({ isOfficer, onNavigate }: { isOfficer: boolean; onNavigate: (workspace: Workspace) => void }) {
  const metrics: Metric[] = isOfficer ? [{ label: 'Total tenders', value: '18', detail: '+4 this month', icon: <FileText />, tone: 'blue' }, { label: 'Bids requiring review', value: '07', detail: '3 high-priority items', icon: <ClipboardCheck />, tone: 'amber' }, { label: 'Average compliance', value: '86.4%', detail: '+5.2% vs last cycle', icon: <ShieldCheck />, tone: 'green' }, { label: 'High-risk bidders', value: '02', detail: 'Needs officer attention', icon: <AlertTriangle />, tone: 'red' }] : [{ label: 'Available tenders', value: '12', detail: '4 closing this week', icon: <FileText />, tone: 'blue' }, { label: 'Draft applications', value: '03', detail: 'Last saved 18 min ago', icon: <ClipboardCheck />, tone: 'amber' }, { label: 'Submitted bids', value: '08', detail: '6 verification complete', icon: <ShieldCheck />, tone: 'green' }, { label: 'Active alerts', value: '02', detail: 'Documents need attention', icon: <AlertTriangle />, tone: 'red' }]
  return <><section className="metric-grid">{metrics.map(metric => <MetricCard key={metric.label} metric={metric} />)}</section><div className="section-grid"><section className="panel tender-panel"><PanelHeading title={isOfficer ? 'Active tender portfolio' : 'Recommended opportunities'} action={isOfficer ? 'View all tenders' : 'Browse tenders'} onClick={() => onNavigate('tenders')} /><div className="table-wrap"><table><thead><tr><th>{isOfficer ? 'Tender' : 'Opportunity'}</th><th>Status</th><th>Deadline</th><th className="numeric">{isOfficer ? 'Bids' : 'Budget'}</th></tr></thead><tbody>{DEMO_TENDERS.map(tender => <tr key={tender.id}><td><strong>{tender.title}</strong><span>{tender.id} · {tender.department}</span></td><td><StatusBadge status={tender.status} /></td><td>{tender.deadline}</td><td className="numeric">{isOfficer ? tender.bids : tender.budget}</td></tr>)}</tbody></table></div></section><section className="panel activity-panel"><PanelHeading title="Recent activity" action="View audit trail" onClick={() => onNavigate('audit')} /><div className="activity-list">{DEMO_ACTIVITY.map(item => <div className="activity-item" key={item.id}><span className={`activity-icon ${item.tone}`}><Activity /></span><div><strong>{item.label}</strong><span>{item.detail}</span><small>{item.time}</small></div></div>)}</div></section></div><section className="trust-banner"><div className="trust-icon"><ShieldCheck /></div><div><strong>Evidence-backed procurement, with officers in control.</strong><span>AI analysis highlights evidence, inconsistencies and risk. It never makes the final qualification decision.</span></div><button onClick={() => onNavigate('audit')}>Review governance <ArrowUpRight /></button></section></>
}

function WorkspacePage({ workspace, isOfficer, onNotice }: { workspace: Workspace; isOfficer: boolean; onNotice: (message: string) => void }) { const titles: Record<Workspace, [string, string]> = { overview: ['Overview', ''], tenders: [isOfficer ? 'Tender portfolio' : 'Available tenders', 'Review active opportunities and submission requirements.'], bids: [isOfficer ? 'Bid review queue' : 'My applications', 'Every submission remains traceable and reviewable.'], documents: ['Document centre', 'Upload, classify and review procurement evidence.'], audit: ['Audit trail', 'A transparent timeline of platform activity and decisions.'] }; return <><div className="workspace-toolbar"><div className="search-box"><Search /><input placeholder="Search by tender, bidder or ID" /></div><button className="button-secondary" onClick={() => onNotice('Filters will be connected to live API data in a later phase.')}>Filter <span>⌄</span></button></div><section className="panel workspace-panel"><PanelHeading title={titles[workspace][0]} action={workspace === 'tenders' && isOfficer ? 'Create tender' : undefined} onClick={() => onNotice('This workflow is scoped for the next approved phase.')} />{workspace === 'tenders' ? <div className="tender-list">{DEMO_TENDERS.map(t => <div className="tender-row" key={t.id}><div className="tender-symbol"><FileText /></div><div className="tender-row-main"><strong>{t.title}</strong><span>{t.id} · {t.department}</span><div className="tag-row">{t.requirements.slice(0, 2).map(requirement => <span className="tag" key={requirement}>{requirement}</span>)}</div></div><div className="tender-row-meta"><StatusBadge status={t.status} /><span>{t.deadline}</span></div><ChevronRight /></div>)}</div> : workspace === 'bids' ? <BidTable isOfficer={isOfficer} /> : workspace === 'documents' ? <EmptyState icon={<FileCheck2 />} title="Document centre is ready" text="Individual uploads, ZIP processing and verification states will be connected in Phase 4 and Phase 5." action="Explore architecture" onClick={() => onNotice('Document service boundary created in src/domain.ts.')} /> : <EmptyState icon={<Activity />} title="Audit events will appear here" text="Every registration, upload, analysis and officer decision will be recorded in the production audit trail." action="View governance policy" onClick={() => onNotice('AI decision support only. Final decisions remain with the Procurement Officer.')} />}</section></> }

function BidTable({ isOfficer }: { isOfficer: boolean }) { return <div className="table-wrap"><table><thead><tr><th>Bidder</th><th>Tender</th><th>Compliance</th><th>Risk</th><th>Status</th></tr></thead><tbody>{DEMO_BIDS.map(bid => <tr key={bid.id}><td><strong>{bid.bidder}</strong><span>{bid.id}</span></td><td>{bid.tender}</td><td><strong className="score">{bid.score}%</strong></td><td><RiskBadge risk={bid.risk} /></td><td><StatusBadge status={bid.status} /></td></tr>)}</tbody></table></div> }

function SideLink({ icon, label, active, onClick }: { icon: ReactNode; label: string; active: boolean; onClick: () => void }) { return <button className={active ? 'side-link active' : 'side-link'} onClick={onClick}>{icon}<span>{label}</span>{active && <span className="active-bar" />}</button> }
function MetricCard({ metric }: { metric: Metric }) { return <article className="metric-card"><div className={`metric-icon ${metric.tone}`}>{metric.icon}</div><div><span>{metric.label}</span><strong>{metric.value}</strong><small>{metric.detail}</small></div><ArrowUpRight className="metric-arrow" /></article> }
function PanelHeading({ title, action, onClick }: { title: string; action?: string; onClick?: () => void }) { return <div className="panel-heading"><h2>{title}</h2>{action && <button onClick={onClick}>{action}<ArrowUpRight /></button>}</div> }
function StatusBadge({ status }: { status: Status }) { const labels: Record<Status, string> = { OPEN: 'Open', IN_REVIEW: 'In review', VERIFIED: 'Verified', REQUIRES_REVIEW: 'Needs review', DRAFT: 'Draft' }; return <span className={`status-badge ${status.toLowerCase()}`}><span />{labels[status]}</span> }
function RiskBadge({ risk }: { risk: Bid['risk'] }) { return <span className={`risk-badge ${risk.toLowerCase()}`}>{risk === 'LOW' ? 'Low risk' : risk === 'MEDIUM' ? 'Medium risk' : 'High risk'}</span> }
function EmptyState({ icon, title, text, action, onClick }: { icon: ReactNode; title: string; text: string; action: string; onClick: () => void }) { return <div className="empty-state"><div className="empty-icon">{icon}</div><h3>{title}</h3><p>{text}</p><button className="button-secondary" onClick={onClick}>{action}<ArrowUpRight /></button></div> }

createRoot(document.getElementById('root')!).render(<App />)
