import { useState } from 'react'
import { createRoot } from 'react-dom/client'
import { Activity, ArrowLeft, ArrowUpRight, Bell, Building2, CheckCircle2, ClipboardCheck, FileText, LayoutDashboard, LogIn, Menu, Plus, ShieldCheck, Sparkles, Upload, X } from 'lucide-react'
import type { UserRole } from './domain'
import './index.css'

type Screen = 'landing' | 'login' | 'register' | 'officer' | 'create-tender' | 'tenders' | 'bidder' | 'apply' | 'review' | 'audit'
type Tender = { tender_id: string; name: string; department?: string; budget: string; deadline?: string; experience: string; description: string; requirements?: string[]; status?: string; bids?: number }
type Bid = { bid_id: string; bidder_name: string; tender_id: string; score?: number; risk?: string; status: string; documents: { name: string; status?: string }[]; submitted_at: string }

const API = (import.meta.env.VITE_API_URL || '').replace(/\/$/, '')
const demoUser = { name: 'Demo officer', email: 'officer@tenderhub.demo', role: 'OFFICER' as UserRole }

function App() {
  const [screen, setScreen] = useState<Screen>('landing')
  const [role, setRole] = useState<UserRole>('OFFICER')
  const [user, setUser] = useState(demoUser)
  const [tenders, setTenders] = useState<Tender[]>([])
  const [bids, setBids] = useState<Bid[]>([])
  const [selectedTender, setSelectedTender] = useState<Tender | null>(null)
  const [notice, setNotice] = useState('')
  const [loading, setLoading] = useState(false)

  async function refresh() { try { const [t, b] = await Promise.all([fetch(`${API}/api/tenders`), fetch(`${API}/api/bids`)]); if (t.ok) setTenders(await t.json()); if (b.ok) setBids(await b.json()) } catch { setNotice('Backend unavailable. Demo mode is active; connect FastAPI to persist changes.') } }
  async function createTender(form: FormData) { setLoading(true); try { const response = await fetch(`${API}/api/tenders`, { method: 'POST', body: form }); if (!response.ok) throw new Error(); const tender = await response.json(); setTenders((items) => [...items, tender]); setSelectedTender(tender); setNotice('Tender saved as a real backend record.'); setScreen('tenders') } catch { setNotice('Tender could not be saved. Check that FastAPI is running on port 8000.') } finally { setLoading(false) } }
  async function submitBid(form: FormData) { if (!selectedTender) return; form.append('tender_id', selectedTender.tender_id); setLoading(true); try { const response = await fetch(`${API}/api/bids`, { method: 'POST', body: form }); if (!response.ok) throw new Error(); const bid = await response.json(); setBids((items) => [...items, bid]); setNotice(`Bid ${bid.bid_id} submitted and locked. Automatic analysis started.`); setScreen('review') } catch { setNotice('Bid could not be submitted. Please check the backend and deadline.') } finally { setLoading(false) } }
  function enter(next: Screen, nextRole?: UserRole) { if (nextRole) { setRole(nextRole); setUser(nextRole === 'OFFICER' ? demoUser : { name: 'Demo vendor', email: 'vendor@tenderhub.demo', role: 'BIDDER' }) }; setScreen(next); refresh() }

  if (screen === 'landing') return <Landing onLogin={() => setScreen('login')} onRegister={() => setScreen('register')} />
  if (screen === 'login' || screen === 'register') return <Auth screen={screen} onBack={() => setScreen('landing')} onDone={(nextRole) => enter(nextRole === 'OFFICER' ? 'officer' : 'bidder', nextRole)} />
  return <Shell role={role} user={user} screen={screen} setScreen={setScreen} notice={notice} clearNotice={() => setNotice('')} onRefresh={refresh}>
    {screen === 'officer' && <OfficerHome tenders={tenders} bids={bids} onCreate={() => setScreen('create-tender')} onTenders={() => setScreen('tenders')} />}
    {screen === 'create-tender' && <CreateTender onCancel={() => setScreen('officer')} onSubmit={createTender} loading={loading} />}
    {screen === 'tenders' && <TenderList role={role} tenders={tenders} onCreate={() => setScreen('create-tender')} onSelect={(t) => { setSelectedTender(t); setScreen(role === 'BIDDER' ? 'apply' : 'review') }} />}
    {screen === 'bidder' && <BidderHome tenders={tenders} bids={bids} onBrowse={() => setScreen('tenders')} onSelect={(t) => { setSelectedTender(t); setScreen('apply') }} />}
    {screen === 'apply' && selectedTender && <Apply tender={selectedTender} onCancel={() => setScreen('tenders')} onSubmit={submitBid} loading={loading} />}
    {screen === 'review' && <Review tenders={tenders} bids={bids} onAnalyze={async (id) => { const r = await fetch(`${API}/api/tenders/${id}/analyze-bidders`, { method: 'POST' }); if (r.ok) { const data = await r.json(); setBids((items) => items.map((b) => data.results.find((x: Bid) => x.bid_id === b.bid_id) ? { ...b, ...data.results.find((x: Bid) => x.bid_id === b.bid_id) } : b)); setNotice('Rule-based analysis completed. Human officer review remains required.') } }} />}
    {screen === 'audit' && <Audit />}
  </Shell>
}

function Landing({ onLogin, onRegister }: { onLogin: () => void; onRegister: () => void }) { return <main className="landing"><div className="landing-nav"><Brand /><span className="environment"><i /> Demo environment</span><div><button className="button-secondary" onClick={onLogin}><LogIn /> Sign in</button><button className="button-primary" onClick={onRegister}>Create account <ArrowUpRight /></button></div></div><section className="hero"><div><p className="eyebrow">SIH26100 · GEM PROCUREMENT</p><h1>Evidence-backed bids.<br /><em>Decisions in control.</em></h1><p className="hero-copy">TenderHub brings tender requirements, bidder evidence and compliance review into one transparent workspace for modern procurement teams.</p><div className="hero-actions"><button className="button-primary" onClick={onRegister}>Start a demo <ArrowUpRight /></button><button className="text-button" onClick={onLogin}>I already have an account <ArrowUpRight /></button></div></div><div className="hero-card"><div className="mini-header"><ShieldCheck /> Compliance overview <span>LIVE</span></div><div className="score-ring"><strong>—</strong><span>No live bids yet</span></div><div className="empty-copy">Create and publish a tender to start receiving bids. No procurement activity is fabricated.</div><div className="mini-row"><span>AI decision support</span><b>Human review required</b></div></div></section><section className="feature-strip"><Feature icon={<FileText />} title="Tender to decision" text="A traceable workflow from requirements to officer decision." /><Feature icon={<Sparkles />} title="AI, with evidence" text="Extraction and analysis clearly marked for human review." /><Feature icon={<ShieldCheck />} title="Secure by design" text="Deadline checks, locked bids and audit-ready activity." /></section></main> }
function Feature({ icon, title, text }: { icon: React.ReactNode; title: string; text: string }) { return <div className="feature"><span>{icon}</span><div><strong>{title}</strong><p>{text}</p></div></div> }
function Brand() { return <div className="brand"><span className="brand-mark"><Building2 /></span><div><strong>TenderHub</strong><small>SIH26100 platform</small></div></div> }
function Auth({ screen, onBack, onDone }: { screen: 'login' | 'register'; onBack: () => void; onDone: (role: UserRole) => void }) { const [role, setRole] = useState<UserRole>('OFFICER'); const [name, setName] = useState(''); return <main className="auth-page"><button className="back-button" onClick={onBack}><ArrowLeft /> Back to home</button><div className="auth-card"><Brand /><div className="auth-title"><p className="eyebrow">{screen === 'login' ? 'WELCOME BACK' : 'CREATE YOUR WORKSPACE'}</p><h1>{screen === 'login' ? 'Sign in to TenderHub' : 'Register for TenderHub'}</h1><p>{screen === 'login' ? 'Use demo access to explore both procurement workflows.' : 'Choose your role and continue with the guided demo.'}</p></div><form onSubmit={(e) => { e.preventDefault(); onDone(role) }}><label>Full name<input value={name} onChange={(e) => setName(e.target.value)} placeholder={screen === 'login' ? 'Demo user' : 'Your full name'} required /></label><label>Email or mobile<input type="text" placeholder="you@company.com" required /></label><label>Password<input type="password" placeholder="At least 8 characters" required /></label>{screen === 'register' && <><label>Organization<input placeholder="Company or department" required /></label><div className="role-pills"><button type="button" className={role === 'OFFICER' ? 'selected' : ''} onClick={() => setRole('OFFICER')}>Procurement Officer</button><button type="button" className={role === 'BIDDER' ? 'selected' : ''} onClick={() => setRole('BIDDER')}>Bidder / Vendor</button></div></>}<button className="button-primary full" type="submit">{screen === 'login' ? 'Continue to dashboard' : 'Create demo account'} <ArrowUpRight /></button></form><p className="demo-note"><ShieldCheck /> Demo OTP mode is labelled and uses no real credentials.</p></div></main> }

function Shell({ role, user, screen, setScreen, notice, clearNotice, children }: { role: UserRole; user: typeof demoUser; screen: Screen; setScreen: (s: Screen) => void; notice: string; clearNotice: () => void; onRefresh: () => void; children: React.ReactNode }) { const links: [Screen, string, React.ReactNode][] = [['officer', 'Overview', <LayoutDashboard />], ['tenders', role === 'OFFICER' ? 'Tenders' : 'Available tenders', <FileText />], ['review', role === 'OFFICER' ? 'Bid review' : 'My applications', <ClipboardCheck />], ['audit', 'Audit trail', <Activity />]]; return <div className="app-shell"><aside className="sidebar"><Brand /><div className="workspace-label">WORKSPACE</div><div className="active-role"><i />{role === 'OFFICER' ? 'Procurement Officer' : 'Bidder / Vendor'}</div><nav>{links.map(([id, label, icon]) => <button key={id} className={screen === id ? 'side-link active' : 'side-link'} onClick={() => setScreen(id)}>{icon}<span>{label}</span></button>)}</nav><div className="sidebar-foot"><div className="ai-note"><Sparkles /><span><b>AI decision support</b>Human review is always required.</span></div><div className="profile"><div className="avatar">{role === 'OFFICER' ? 'DO' : 'DV'}</div><span><b>{user.name}</b>{role === 'OFFICER' ? 'Procurement workspace' : 'Vendor workspace'}</span></div></div></aside><main className="main-content"><header className="topbar"><button className="mobile-menu"><Menu /></button><div className="breadcrumbs"><span>Workspace</span><ArrowUpRight /><b>{screen.replace('-', ' ')}</b></div><div className="top-actions"><span className="environment"><i /> Demo environment</span><button className="icon-button"><Bell /><sup>0</sup></button><div className="top-avatar">{role === 'OFFICER' ? 'DO' : 'DV'}</div></div></header><div className="page-content">{notice && <div className="notice"><CheckCircle2 /><span>{notice}</span><button onClick={clearNotice}><X /></button></div>}{children}</div></main></div> }

function OfficerHome({ tenders, bids, onCreate, onTenders }: { tenders: Tender[]; bids: Bid[]; onCreate: () => void; onTenders: () => void }) { const metrics = [['Total tenders', tenders.length, 'Created in workspace'], ['Bids requiring review', bids.length, bids.length ? 'Awaiting officer review' : 'No bids submitted yet'], ['Average compliance', bids.length ? `${Math.round(bids.reduce((n, b) => n + (b.score || 0), 0) / bids.length)}%` : '—', bids.length ? 'Across analysed bids' : 'Available after analysis'], ['High-risk bidders', bids.filter((b) => b.risk === 'HIGH').length, 'Requires attention']]; return <><PageHeading eyebrow="PROCUREMENT CONTROL CENTRE" title="Officer overview" text="Create tenders, review evidence and keep every decision accountable." action={<button className="button-primary" onClick={onCreate}><Plus /> Create tender</button>} /> <div className="metric-grid">{metrics.map(([label, value, detail]) => <div className="metric-card" key={String(label)}><span>{label}</span><strong>{value}</strong><small>{detail}</small></div>)}</div><div className="section-grid"><Panel title="Active tender portfolio" action="View tenders" onClick={onTenders}>{tenders.length ? tenders.map((t) => <div className="list-row" key={t.tender_id}><FileText /><span><b>{t.name}</b><small>{t.tender_id} · {t.status || 'DRAFT'}</small></span><ArrowUpRight /></div>) : <Empty icon={<FileText />} title="No tenders published yet" text="Create your first tender to begin the officer-to-bidder workflow." action="Create tender" onClick={onCreate} />}</Panel><Panel title="Recent activity"><Empty icon={<Activity />} title="No activity yet" text="Registration, tender and bid events will appear here." /></Panel></div><div className="trust-banner"><ShieldCheck /><span><b>AI decision support only.</b> Final qualification or disqualification must be decided by the Procurement Officer.</span></div></> }
function BidderHome({ tenders, bids, onBrowse, onSelect }: { tenders: Tender[]; bids: Bid[]; onBrowse: () => void; onSelect: (t: Tender) => void }) { return <><PageHeading eyebrow="VENDOR WORKSPACE" title="Bidder overview" text="Find opportunities, prepare evidence and track your submissions." action={<button className="button-primary" onClick={onBrowse}>Browse tenders <ArrowUpRight /></button>} /><div className="metric-grid"><div className="metric-card"><span>Available tenders</span><strong>{tenders.length}</strong><small>Open opportunities</small></div><div className="metric-card"><span>Draft applications</span><strong>0</strong><small>No drafts saved yet</small></div><div className="metric-card"><span>Submitted bids</span><strong>{bids.length}</strong><small>{bids.length ? 'Locked submissions' : 'No bids submitted yet'}</small></div></div><Panel title="Recommended opportunities">{tenders.length ? tenders.slice(0, 3).map((t) => <div className="list-row" key={t.tender_id} onClick={() => onSelect(t)}><FileText /><span><b>{t.name}</b><small>{t.tender_id} · Deadline {t.deadline || 'Not set'}</small></span><ArrowUpRight /></div>) : <Empty icon={<FileText />} title="No published tenders yet" text="The officer must publish a tender before bidders can apply." action="Refresh opportunities" onClick={onBrowse} />}</Panel></> }
function PageHeading({ eyebrow, title, text, action }: { eyebrow: string; title: string; text: string; action?: React.ReactNode }) { return <div className="page-heading"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{text}</p></div>{action}</div> }
function Panel({ title, action, onClick, children }: { title: string; action?: string; onClick?: () => void; children: React.ReactNode }) { return <section className="panel"><div className="panel-heading"><h2>{title}</h2>{action && <button onClick={onClick}>{action} <ArrowUpRight /></button>}</div>{children}</section> }
function Empty({ icon, title, text, action, onClick }: { icon: React.ReactNode; title: string; text: string; action?: string; onClick?: () => void }) { return <div className="empty-state"><div>{icon}</div><h3>{title}</h3><p>{text}</p>{action && <button className="button-secondary" onClick={onClick}>{action} <ArrowUpRight /></button>}</div> }
function TenderList({ role, tenders, onCreate, onSelect }: { role: UserRole; tenders: Tender[]; onCreate: () => void; onSelect: (t: Tender) => void }) { return <><PageHeading eyebrow={role === 'OFFICER' ? 'TENDER PORTFOLIO' : 'OPPORTUNITIES'} title={role === 'OFFICER' ? 'Tender portfolio' : 'Available tenders'} text="Only real records created in this workspace are shown." action={role === 'OFFICER' ? <button className="button-primary" onClick={onCreate}><Plus /> Create tender</button> : undefined} /><Panel title={`${tenders.length} tender${tenders.length === 1 ? '' : 's'}`}>{tenders.length ? <div className="tender-list">{tenders.map((t) => <button className="tender-row" key={t.tender_id} onClick={() => onSelect(t)}><FileText /><span><b>{t.name}</b><small>{t.tender_id} · {t.description}</small></span><span className="tag">{t.status || 'DRAFT'}</span><ArrowUpRight /></button>)}</div> : <Empty icon={<FileText />} title="No tender records" text={role === 'OFFICER' ? 'Create and publish a tender to make it available to vendors.' : 'No published tender is available yet.'} action={role === 'OFFICER' ? 'Create tender' : undefined} onClick={onCreate} />}</Panel></> }
function CreateTender({ onCancel, onSubmit, loading }: { onCancel: () => void; onSubmit: (form: FormData) => void; loading: boolean }) { return <><PageHeading eyebrow="NEW PROCUREMENT" title="Create a tender" text="Define the opportunity and publish it when requirements are reviewed." /><form className="form-card" onSubmit={(e) => { e.preventDefault(); onSubmit(new FormData(e.currentTarget)) }}><div className="form-grid"><label>Tender title<input name="name" required placeholder="Medical equipment procurement" /></label><label>Department<input name="department" placeholder="Health procurement" /></label><label>Estimated budget<input name="budget" required placeholder="₹ 25,00,000" /></label><label>Bid deadline<input name="deadline" type="datetime-local" required /></label><label>Minimum experience<input name="experience" required placeholder="5 years in relevant work" /></label><label>Required turnover<input name="turnover" placeholder="₹ 50,00,000" /></label></div><label>Description<textarea name="description" required placeholder="Describe the scope, eligibility and deliverables." /></label><label className="upload-box"><Upload /> Tender documents or ZIP<input name="documents" type="file" multiple accept=".pdf,.png,.jpg,.jpeg,.zip" /></label><div className="form-actions"><button type="button" className="button-secondary" onClick={onCancel}>Save as draft</button><button className="button-primary" disabled={loading} type="submit">{loading ? 'Saving…' : 'Save & publish tender'} <ArrowUpRight /></button></div></form></> }
function Apply({ tender, onCancel, onSubmit, loading }: { tender: Tender; onCancel: () => void; onSubmit: (form: FormData) => void; loading: boolean }) { return <><PageHeading eyebrow="BID APPLICATION" title={tender.name} text={`${tender.tender_id} · Complete all required fields before submission.`} /><form className="form-card" onSubmit={(e) => { e.preventDefault(); onSubmit(new FormData(e.currentTarget)) }}><div className="stepper"><b>1 Company</b><span>2 Eligibility</span><span>3 Documents</span><span>4 Review</span></div><div className="form-grid"><label>Legal company name<input name="name" required placeholder="Aarav Ventures Pvt Ltd" /></label><label>Authorized person<input name="authorized_person" required placeholder="Full name" /></label><label>Email<input name="email" type="email" required placeholder="vendor@company.com" /></label><label>Mobile<input name="mobile" required placeholder="+91 98765 43210" /></label><label>City<input name="city" required placeholder="New Delhi" /></label><label>Years of experience<input name="experience" type="number" min="0" required placeholder="5" /></label><label>Annual turnover<input name="turnover" required placeholder="₹ 50,00,000" /></label><label>PAN<input name="pan" placeholder="ABCDE1234F" /></label><label>GSTIN<input name="gstin" placeholder="22ABCDE1234F1Z5" /></label><label>Bid amount<input name="bid_amount" required placeholder="₹ 20,00,000" /></label></div><label>Eligibility declaration<textarea name="declaration" required placeholder="Confirm relevant experience, document authenticity and compliance." /></label><label className="upload-box"><Upload /> Upload documents or complete ZIP<input name="documents" type="file" multiple accept=".pdf,.png,.jpg,.jpeg,.zip" /></label><label className="check"><input type="checkbox" required /> I confirm the information is accurate and understand that the officer makes the final decision.</label><div className="form-actions"><button type="button" className="button-secondary" onClick={onCancel}>Save draft</button><button className="button-primary" disabled={loading} type="submit">{loading ? 'Submitting…' : 'Submit locked bid'} <ArrowUpRight /></button></div></form></> }
function Review({ tenders, bids, onAnalyze }: { tenders: Tender[]; bids: Bid[]; onAnalyze: (id: string) => void }) { return <><PageHeading eyebrow="EVIDENCE REVIEW" title="Bid review queue" text="Analysis is explainable and always subject to officer approval." /><Panel title={`Submitted bids · ${bids.length}`}>{bids.length ? <div className="table-wrap"><table><thead><tr><th>Bidder</th><th>Tender</th><th>Compliance</th><th>Risk</th><th>Source</th><th>Action</th></tr></thead><tbody>{bids.map((b) => <tr key={b.bid_id}><td><b>{b.bidder_name}</b><small>{b.bid_id}</small></td><td>{tenders.find((t) => t.tender_id === b.tender_id)?.name || b.tender_id}</td><td><strong>{b.score ? `${b.score}%` : 'Pending'}</strong></td><td><span className={`risk ${String(b.risk || 'REQUIRES_REVIEW').toLowerCase()}`}>{b.risk || 'Requires review'}</span></td><td><span className="tag">Rule-based fallback</span></td><td><button className="small-button" onClick={() => onAnalyze(b.tender_id)}>Analyse</button></td></tr>)}</tbody></table></div> : <Empty icon={<ClipboardCheck />} title="No bids requiring review" text="Bids will appear here after a bidder submits an application." />}</Panel><div className="trust-banner"><ShieldCheck /><span><b>AI decision support only.</b> Government verification is not fabricated; unavailable providers are marked clearly.</span></div></> }
function Audit() { return <><PageHeading eyebrow="GOVERNANCE" title="Audit trail" text="A transparent record of registration, uploads, analysis and officer decisions." /><Panel title="Activity history"><Empty icon={<Activity />} title="No audit events yet" text="Events will appear here as real users create tenders and submit bids." /></Panel></> }

createRoot(document.getElementById('root')!).render(<App />)
